### ISSUE TITLE
Search::Elasticsearch::Bulk::update doesn't accept same params as direct update

### ISSUE THREAD

**Issue by celogeek** [elasticsearch/elasticsearch-perl#53]
I use this 

```
   $self->els->update(
        {   id              => "MYID",
            index => "X", type => "Y",
            body => {
                script_id       => "MyScriptID",
                scripted_upsert => 1,
                upsert          => {},
                params          => { expire_at => $expire_at * 1000 },
            }
        });
```

The bulk doesn't support "script_id" and "scripted_upsert". Does the bulk API forbid that ?

**Comment by clintongormley** [comment]
Hi @celogeek 

This seems to work just fine:

    use strict;
    use warnings;
    
    use Search::Elasticsearch;
    
    my $es = Search::Elasticsearch->new( trace_to => 'Stderr' );
    
    $es->index(
        index => '_scripts',
        type  => 'groovy',
        id    => 'my_script',
        body  => { script => 'ctx._source.foo=foo' }
    );
    
    $es->bulk(
        body => [
            { update=>{  _index => 'test',
                _type  => 'test',
                _id    => 1
            }},
            {   scripted_upsert => 1,
                script_id       => 'my_script',
                params          => { foo => 'bar' },
                upsert          => {}
            }
        ]
    );
    
    my $doc = $es->get( index => 'test', type => 'test', id => 1 );
    
Perhaps you're using an older version of Elasticsearch?
