### ISSUE TITLE
use Moo statement wrong

### ISSUE THREAD

**Issue by singingfish** [elasticsearch/elasticsearch-perl#56]
use Moo 1.003; 

on line 3 should be:

    use Moo 1.003 ();

because  Search::ElasticSearch is a factory class.  The statement is only there to indicate the minimum version is required and it shouldn't be importing anything from Moo into that namespace.

**Comment by clintongormley** [comment]
Have you tried changing it and running the test suite?

You'll find that Search::Elasticsearch::Async (which `extends` Search::Elasticsearch) no longer works as expected.

**Comment by singingfish** [comment]
In that case I would suggest that some documentation is in order.  Overriding new() in a Moo class is not something you would normally expect to see.  As per Apache2::Request a short amount of documentation on subclassing would be useful.  Something as short as:

"If you want to subclass Search::ElasticSearch, see Search::ElasticSearch::Async for an example"

**Comment by shadowcat-mst** [comment]
Then Search::Elasticsearch::Async should be doing 'use base' or 'use parent'.

If you're going to write something that's not-a-real constructor, don't tell Moo it's a class - that might be currently working but basically buggering around with new() in an M* class is a path to doom, and just explicitly letting it not be a 'real' class is going to be much nicer.

**Comment by clintongormley** [comment]
true - fixed
